# resolver: nightly-2022-03-23 # ghc-9.2.2
# resolver: lts-19.0 # ghc-9.0.2
# resolver: lts-18.28 # ghc-8.10.7
resolver: lts-18.6 # ghc-8.10.4 # Currently the only version that seems to work with LiquidHaskell
packages:
  - .
allow-newer: true
extra-deps:
  # For Massiv benchmarks:
  - massiv-1.0.1.1
  - scheduler-2.0.0
  # For LiquidHaskell:
  - text-format-0.3.2
  - Diff-0.3.4
  - optparse-applicative-0.16.1.0
  - liquid-fixpoint-0.8.10.2
  - liquidhaskell-0.8.10.2
  - liquid-base-4.14.1.0
  - liquid-ghc-prim-0.6.1
